name: silly_workflow
on:
  push: #Action fires anytime there is a push to the following branches
    branches:
      - main
    paths:
      - documentation/**
jobs:
  set-root-url:
    runs-on: ubuntu-latest
    steps:
      - name: Set root url
        run: echo 'silly'
